@ProcessManagement_HostAddress = http://192.168.1.13:5000


GET {{ProcessManagement_HostAddress}}/api/vitrioftpham

###

GET {{ProcessManagement_HostAddress}}/api/vitrioftpham

###

GET {{ProcessManagement_HostAddress}}/api/vitrioftpham

###
